### PR TITLE
Update to latest husky and commitlint

### PR DESCRIPTION
**Pull request by ZachHaber**
validate-commit-msg has been deprecated and suggests commitlint as a replacement.

In addition, the change from escaped double quotes to single quotes in the package.json was breaking for me locally (windows).

### CODE REVIEW

**Comment by ZachHaber** [comment]
Also, side note: What are your thoughts on using prettier?

**Comment by lamweili** [comment]
We are using `prettier` in the main [`log4js`](https://github.com/log4js-node/log4js-node) repository.
If you want, you can go ahead.

I have converted your PR to a draft.
When you are done with all the devDependencies, mark it ready and I'll merge it. :hugs:

**Comment by ZachHaber** [comment]
@peteriman, this is no longer using the .travis.yml, correct? If so, we can remove `codecov` and it's script, as they are no longer used in the new workflow.

**Comment by lamweili** [comment]
@ZachHaber Yes, Travis CI stopped working for open source builds a long time ago.
We are now using GH action that runs the build for every PR. Go ahead and clean the devDependencies.

**Comment by lamweili** [comment]
@ZachHaber Do you still have any more changes for this repository?
Or can I sort of code freeze and prepare to release a version to npm?

**Comment by ZachHaber** [comment]
Yeah, i have a few more things I was planning.

**Comment by lamweili** [comment]
Noted. I shall hold it on.

**Pull request merged**
